#!/usr/bin/env bash
#
# Draken one-command installer for a fresh Debian/Ubuntu server.
#
#   curl -fsSL https://raw.githubusercontent.com/Teoremadepierre/Draken/main/install.sh | sudo bash -s -- seo.tudominio.com
#
# Or, from a clone:
#   sudo ./install.sh seo.tudominio.com
#
# It installs Python and Caddy, creates a service user, sets up the app as a
# systemd unit, generates a secret key and an admin password, and puts Caddy in
# front so HTTPS is issued automatically. It prints the URL and the password at
# the end.
#
# Safe to re-run: it updates the code and restarts rather than starting over.

set -euo pipefail

DOMAIN="${1:-}"
BRANCH="${DRAKEN_BRANCH:-claude/backlinks-seo-tool-study-2tlk0x}"
REPO="${DRAKEN_REPO:-https://github.com/Teoremadepierre/Draken}"
APP_USER="draken"
APP_HOME="/home/${APP_USER}"
APP_DIR="${APP_HOME}/draken"

say()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run this with sudo."

if [ -z "$DOMAIN" ]; then
    cat >&2 <<USAGE
Usage: sudo ./install.sh <domain>

Example:
    sudo ./install.sh seo.tudominio.com

Point the domain's A record at this server's IP first, or Caddy cannot get a
certificate. To run without a domain (plain HTTP on port 8000), pass: --no-tls
USAGE
    exit 1
fi

NO_TLS=false
[ "$DOMAIN" = "--no-tls" ] && { NO_TLS=true; DOMAIN=""; }

say "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq --no-install-recommends \
    python3 python3-venv python3-pip git curl ca-certificates debian-keyring \
    debian-archive-keyring apt-transport-https >/dev/null

if [ "$NO_TLS" = false ] && ! command -v caddy >/dev/null 2>&1; then
    say "Installing Caddy (automatic HTTPS)"
    curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
        | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
    apt-get update -qq
    apt-get install -y -qq caddy >/dev/null
fi

id -u "$APP_USER" >/dev/null 2>&1 || {
    say "Creating the ${APP_USER} service user"
    useradd --system --create-home --shell /bin/bash "$APP_USER"
}

if [ -d "${APP_DIR}/.git" ]; then
    say "Updating the existing installation"
    sudo -u "$APP_USER" git -C "$APP_DIR" fetch --quiet origin "$BRANCH"
    sudo -u "$APP_USER" git -C "$APP_DIR" checkout --quiet "$BRANCH"
    sudo -u "$APP_USER" git -C "$APP_DIR" reset --hard --quiet "origin/${BRANCH}"
else
    say "Cloning ${REPO} (${BRANCH})"
    sudo -u "$APP_USER" git clone --quiet --branch "$BRANCH" "$REPO" "$APP_DIR"
fi

say "Installing the Python environment"
sudo -u "$APP_USER" python3 -m venv "${APP_DIR}/.venv" 2>/dev/null || true
sudo -u "$APP_USER" "${APP_DIR}/.venv/bin/pip" install --quiet --upgrade pip
sudo -u "$APP_USER" "${APP_DIR}/.venv/bin/pip" install --quiet -e "${APP_DIR}/backend"

ENV_FILE="${APP_DIR}/.env"
if [ ! -f "$ENV_FILE" ]; then
    say "Generating configuration and an admin password"
    SECRET="$(openssl rand -hex 32)"
    ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
    ADMIN_HASH="$(sudo -u "$APP_USER" "${APP_DIR}/.venv/bin/python" \
        -m draken.cli.main hash-password "$ADMIN_PASSWORD" 2>/dev/null | head -1)"

    PUBLIC_URL="http://$(hostname -I | awk '{print $1}'):8000"
    [ -n "$DOMAIN" ] && PUBLIC_URL="https://${DOMAIN}"

    cat > "$ENV_FILE" <<ENVEOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DRAKEN_ENV=production
DRAKEN_SECRET_KEY=${SECRET}
DRAKEN_HOST=127.0.0.1
DRAKEN_PORT=8000
DRAKEN_DATABASE_URL=sqlite:///${APP_DIR}/data/draken.db

DRAKEN_AUTH_ENABLED=true
DRAKEN_ADMIN_USER=admin
DRAKEN_ADMIN_PASSWORD_HASH=${ADMIN_HASH}

DRAKEN_USER_AGENT=DrakenSEO/0.1 (+${PUBLIC_URL}/bot)
DRAKEN_CORS_ORIGINS=${PUBLIC_URL}

# Submissions stay in dry-run until you have reviewed what they would send.
DRAKEN_SUBMISSIONS_DRY_RUN=true
DRAKEN_SUBMISSIONS_REQUIRE_APPROVAL=true
DRAKEN_OUTREACH_SEND_ENABLED=false

# --- Optional: add the keys you have -------------------------------------
# Real measured data for your own site (both free):
# DRAKEN_GSC_SERVICE_ACCOUNT_FILE=${APP_DIR}/gsc-service-account.json
# DRAKEN_GSC_SITE_URL=sc-domain:tudominio.com
# DRAKEN_BING_WEBMASTER_API_KEY=
# AI visibility and the in-app assistant:
# DRAKEN_ANTHROPIC_API_KEY=
# DRAKEN_PERPLEXITY_API_KEY=
ENVEOF
    chown "${APP_USER}:${APP_USER}" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "$ADMIN_PASSWORD" > "${APP_HOME}/.draken-admin-password"
    chown "${APP_USER}:${APP_USER}" "${APP_HOME}/.draken-admin-password"
    chmod 600 "${APP_HOME}/.draken-admin-password"
else
    say "Keeping the existing .env"
    ADMIN_PASSWORD="$(cat "${APP_HOME}/.draken-admin-password" 2>/dev/null || echo '(unchanged)')"
fi

say "Creating the database and loading the source catalog"
sudo -u "$APP_USER" mkdir -p "${APP_DIR}/data" "${APP_HOME}/logs"
sudo -u "$APP_USER" "${APP_DIR}/.venv/bin/python" -m draken.cli.main init-db >/dev/null

say "Installing the systemd service"
sed -e "s#/home/draken/draken#${APP_DIR}#g" \
    -e "s#/home/draken/logs#${APP_HOME}/logs#g" \
    "${APP_DIR}/deploy/systemd/draken.service" > /etc/systemd/system/draken.service
systemctl daemon-reload
systemctl enable --now draken >/dev/null 2>&1 || systemctl restart draken
sleep 3

if ! systemctl is-active --quiet draken; then
    warn "The service did not start. Logs:"
    journalctl -u draken -n 30 --no-pager >&2
    die "Fix the error above and re-run this script."
fi

if [ "$NO_TLS" = false ]; then
    say "Configuring Caddy for ${DOMAIN}"
    sed "s/seo.example.com/${DOMAIN}/" "${APP_DIR}/deploy/caddy/Caddyfile" > /etc/caddy/Caddyfile
    mkdir -p /var/log/caddy && chown caddy:caddy /var/log/caddy
    systemctl reload caddy 2>/dev/null || systemctl restart caddy
    PUBLIC_URL="https://${DOMAIN}"
else
    warn "Running without TLS. Opening port 8000 directly."
    sed -i 's/^DRAKEN_HOST=127.0.0.1/DRAKEN_HOST=0.0.0.0/' "$ENV_FILE"
    sed -i "s#--host 127.0.0.1#--host 0.0.0.0#" /etc/systemd/system/draken.service
    systemctl daemon-reload && systemctl restart draken
    PUBLIC_URL="http://$(hostname -I | awk '{print $1}'):8000"
fi

say "Scheduling the weekly sweep"
CRON_FILE=/etc/cron.d/draken
cat > "$CRON_FILE" <<CRONEOF
# Draken scheduled jobs. Project 1 is the first project you create.
SHELL=/bin/bash
0 3 * * 1 ${APP_USER} cd ${APP_DIR} && .venv/bin/python -m draken.cli.main sweep 1 >> ${APP_HOME}/logs/sweep.log 2>&1
0 6 * * * ${APP_USER} cd ${APP_DIR} && .venv/bin/python -m draken.cli.main keywords track 1 >> ${APP_HOME}/logs/ranks.log 2>&1
CRONEOF
chmod 644 "$CRON_FILE"

HEALTH="$(curl -fsS "http://127.0.0.1:8000/api/health" 2>/dev/null || echo '')"
[ -n "$HEALTH" ] || warn "The local health check did not respond; check: journalctl -u draken -f"

cat <<DONE

  ────────────────────────────────────────────────────────────────
   Draken is running.

     URL:       ${PUBLIC_URL}
     User:      admin
     Password:  ${ADMIN_PASSWORD}

   The password is also in ${APP_HOME}/.draken-admin-password

   First steps:
     1. Open the URL and sign in.
     2. Paste your site's address into "Escáner".
     3. Connect Search Console in "Fuentes de datos" for real data.

   Useful:
     systemctl status draken
     journalctl -u draken -f
     ${APP_DIR}/.venv/bin/python -m draken.cli.main report 1
  ────────────────────────────────────────────────────────────────

DONE
